version: '3.8.0'

volumes:
  local_postgres:

services:
  database:
    image: postgres:16.4
    container_name: test_database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "local_postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    profiles:
      - api-deps
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build:
      context: api
      dockerfile: ./Dockerfile
    container_name: test_api
    ports:
      - "3000:3000"
    volumes:
      - "./api:/home/node/app"
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - api-deps
    environment:
      - DB_HOST=database
      - DATABASE_URL=postgresql://test:test@database:5432/test?schema=public
    env_file:
      - "./api/.env"
